name: Lint and Format

on:
  pull_request:
  push:
    branches:
      - "*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@7cdaf2fbc075e6f3b9ca94cfd6cec5adc8a75622 #v4
      - name: Set up Python 3.11
        uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c #v5
        with:
          python-version: 3.11
      - name: Install and configure Poetry
        uses: snok/install-poetry@93ada01c735cc8a383ce0ce2ae205a21c415379b #v1
        with:
          version: latest
          virtualenvs-create: false
      - name: Install dependencies
        run: poetry install
      - name: Run Format check
        run: poetry run ruff format --check
      - name: Run Lint
        run: poetry run ruff check
