name: Lint and Format

on:
  push:
    branches:
      - "*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.7
          virtualenvs-create: false
      - name: Install dependencies
        run: poetry install
      - name: Run Format check
        run: poetry run ruff format --check
      - name: Run Lint
        run: poetry run ruff check
