name: Run Tests

on:
  pull_request:
    types: [opened, reopened]
  push:
    branches:
      - "*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          version: latest
          virtualenvs-create: false
      - name: Install dependencies
        run: poetry install
      - name: Run Format check
        run: poetry run pytest
